const SET_IS_HERO_DICE_SHOWN = 'SET_IS_HERO_DICE_SHOWN'
const SET_IS_FOE_DICE_SHOWN = 'SET_IS_FOE_DICE_SHOWN'
const SET_IS_HIT_MESSAGE_SHOWN = 'SET_IS_HIT_MESSAGE_SHOWN'

export {
  SET_IS_HERO_DICE_SHOWN,
  SET_IS_FOE_DICE_SHOWN,
  SET_IS_HIT_MESSAGE_SHOWN,
}
